############################################
#      CONFIGURATION FOR OSCYS      #
############################################

tei_solr_xsl: projects/oscys/scripts/solr_transform_tei.xsl
tei_html_xsl: projects/oscys/scripts/tei.p5.xsl

###################
#   Development   #
###################

development:
  # solr information
  solr_path: http://server.unl.edu:port/path/
  solr_core: api_oscys

  # NOTE! If you are altering ANY of the xsl_params you must
  #   copy over ALL of them to the project specific config file
  xsl_params:
    fig_location: http://server.unl.edu/figures/oscys/
    file_location: http://server.unl.edu/data/projects/
    figures: true
    fw: false        # form works (page nums, etc)
    pb: true        # page breaks
    project: O\ Say\ Can\ You\ See
    slug: oscys

##################
#   Production   #
##################
production:
  # solr information
  solr_path: http://server.unl.edu:port/path/
  solr_core: api_oscys

  # NOTE! If you are altering ANY of the xsl_params you must
  #   copy over ALL of them to the project specific config file
  xsl_params:
    fig_location: http://server.unl.edu/figures/oscys/
    file_location: http://server.unl.edu/data/projects/
    figures: true
    fw: false        # form works (page nums, etc)
    pb: true        # page breaks
    project: O\ Say\ Can\ You\ See
    slug: oscys
