# This config file should be copied and added at  projects/<project_name>/config/config.yml
# It should be specific to each project

# The name of the core, not the path to the core
# TODO if the names are different on test and production this code will need to be changed
solr_core: api_oscys_test_alpha
override_scripts:
  tei: projects/oscys/scripts/solr_transform_tei.xsl
xslt:
  test:
    fig_location: http://jetson.unl.edu/oscys_figures/
    file_location: http://rosie.unl.edu/data/projects/
    figures: true 
    fw: true        # form works (page nums, etc)
    pb: true        # page breaks
    project: oscys 
    slug: oscys
    override_tei_xslt: true
  production:
    fig_location: http://cdrhsites.unl.edu/data_images/projects/example/figures/
    file_location: http://cdrhsites.unl.edu/data/projects/
    figures: true
    fw: true        # form works (page nums, etc)
    pb: true        # page breaks
    project: full_name_of_project
    slug: short_name_of_project
    override_tei_xslt: true
